### ISSUE TITLE
Segfault, introduced in da88f78

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#139]
Hi, i know that i can be pain in the ass, i'm sorry about it. But you introduced a segfault with da88f78.
879cd62 works ok. With da88f78 cmst segfaults if one power off the active technoloy. Tracked it down to:

```
[New Thread 0x7fffeaf48700 (LWP 8938)]

Program received signal SIGSEGV, Segmentation fault.
0x00005555555946cc in QMap<QString, QVariant>::value (adefaultValue=..., akey=..., this=0x8)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:616
616         Node *n = d->findNode(akey);
```
```
(gdb) bt
#0  0x00005555555946cc in QMap<QString, QVariant>::value (adefaultValue=..., akey=..., this=0x8)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:616
#1  ControlBox::dbsServicesChanged (this=this@entry=0x7fffffffd6e0, vlist=..., removed=..., msg=...)
    at code/control_box/controlbox.cpp:889
#2  0x00005555555f4f08 in ControlBox::qt_static_metacall (_o=_o@entry=0x7fffffffd6e0, 
    _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=13, _a=_a@entry=0x7fffffffc830)
    at moc_files/moc_controlbox.cpp:372
#3  0x00005555555f5de5 in ControlBox::qt_metacall (this=0x7fffffffd6e0, 
    _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fffffffc830) at moc_files/moc_controlbox.cpp:557
#4  0x00007ffff7f63913 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#5  0x00007ffff6e8de61 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff78ebc7b in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff78a8ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff78ae4b6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6e5e5ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6e609a6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6eb4633 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff5b6dfd7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff5b6e230 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff5b6e2dc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6eb4a3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6e5bd6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff6e63e0c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x000055555556a30c in main (argc=2, argv=<optimized out>) at code/main.cpp:188
```
which in fact points to the changed file  a/apps/cmstapp/code/control_box/controlbox.cpp (#1..:889)

**Comment by andrew-bibb** [comment]
Hey, no problem.  Segfaults are serious issues, and it was a huge help having the line identified.

Problem was actually the services list going to zero, which you were seeing when you turned off the last technology.  I had a couple of VPN services provisioned from my testing, and so long as a provisioning file exists the services inside exist, whether or not the technology is on.  I was not seeing it at first since my service list never went to zero.  Once I removed the provisioning file it segfaulted exactly as you described.
